### ISSUE TITLE
Sett opp Suksess-seksjon

### ISSUE THREAD

**Issue by RasmusKodehode** [Kodeverket-AS/project-teamwork#5]
components/Success.tsx

Noen av våre kunder er også inkludert i denne komponenten

**Comment by kristian-koningsberg** [comment]
Basically ferdig. Tar inn data fra Sanity., holder den åpen intil videre

**Comment by kristian-koningsberg** [comment]
Tar inn data fra Sanity.

**Comment by kristian-koningsberg** [comment]
Sanity dataen er fortsatt ikke den endelige dataen.
